[package]
name = "request_evil"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "1.5"
log = "0.4"
pretty_env_logger = "0.4"
